on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Test with pytest
        run: |
          cd backend && pytest test.py

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: azure acr login
        run: |
          az acr login --name aminab15

      - name: build and push images
        run: |
          cd backend
          docker build -t b15front .
          docker build -t b15back .
          docker tag b15front:latest aminab15.azurecr.io/b15front:v1
          docker tag b15back:latest aminab15.azurecr.io/b15back:v1
          docker push aminab15.azurecr.io/b15front:v1
          docker push aminab15.azurecr.io/b15back:v1

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az container delete --name aminab15-ajax --resource-group gr_aminab15 --yes
            az container create --resource-group gr_aminab15 --name aminab15-ajax \
              --image aminab15.azurecr.io/b15front:v1 \
              --cpu 1 --memory 1 \
              --ports 8000 \
              --dns-name-label aminab15-cluestering \
              --registry-login-server aminab15.azurecr.io \
              --registry-username aminab15 \
              --registry-password ${{ secrets.AZURE_REGISTRY }}

            az container delete --name aminab15-ajax --resource-group gr_aminab15 --yes
            az container create --resource-group gr_aminab15 --name aminab15-ajax \
              --image aminab15.azurecr.io/b15back:v1 \
              --cpu 1 --memory 1 \
              --ports 8000 \
              --dns-name-label aminab15-cluestering \
              --registry-login-server aminab15.azurecr.io \
              --registry-username aminab15 \
              --registry-password ${{ secrets.AZURE_CREDENTIALS }}